import { Navigate, type RouteObject } from 'react-router'
import OwnerLayout from '@/components/Owner/OwnerLayout'
import NotFoundScreen from '@/components/NotFoundScreen/NotFoundScreen'
import {
  DisabledAccountPage,
  EmployeesCreatePage,
  EmployeesEditPage,
  EmployeesListPage,
  EmployeesPermissionsEditPage,
  PasswordEditPage,
  ProfileEditPage,
  SessionsListPage,
} from './owner.pages'
import {
  AdministrationSummaryPage,
  AppointmentsClinicsEditPage,
  AppointmentsListPage,
  BatchesListPage,
  BillingListPage,
  BillingSummaryPage,
  CareSummaryPage,
  ClientsCreatePage,
  ClientsEditPage,
  ClientsListPage,
  ClinicListPage,
  FinanceListPage,
  GroomingListPage,
  GroomingSummaryPage,
  InventoryListPage,
  InventorySummaryPage,
  LaboratorySummaryPage,
  MarketingSummaryPage,
  MovementsListPage,
  PatientsCreatePage,
  PatientsEditPage,
  PatientsListPage,
  PortalsListPage,
  ReceptionSummaryPage,
  SettingsEditPage,
  UsersListPage,
  VisitsListPage,
} from './employee.pages'

const ownerRoutes: RouteObject[] = [
  {
    element: <OwnerLayout />,
    children: [
      { path: '/', element: <Navigate to="/reception" replace /> },
      { path: '/marketing', element: <MarketingSummaryPage /> },
      { path: '/portals', element: <PortalsListPage /> },
      { path: '/appointments-clinics', element: <AppointmentsClinicsEditPage /> },
      { path: '/reception', element: <ReceptionSummaryPage /> },
      { path: '/appointments', element: <AppointmentsListPage /> },
      { path: '/reception-visits', element: <VisitsListPage scope="all" /> },
      { path: '/care', element: <CareSummaryPage /> },
      { path: '/visits', element: <VisitsListPage scope="ambulatory" /> },
      { path: '/grooming-home', element: <GroomingSummaryPage /> },
      { path: '/grooming-visits', element: <VisitsListPage scope="grooming" /> },
      { path: '/grooming', element: <GroomingListPage /> },
      { path: '/laboratory', element: <LaboratorySummaryPage /> },
      { path: '/lab-visits', element: <VisitsListPage scope="laboratory" /> },
      { path: '/clinic', element: <ClinicListPage /> },
      { path: '/inventory-home', element: <InventorySummaryPage /> },
      { path: '/inventory', element: <InventoryListPage /> },
      { path: '/inventory-batches', element: <BatchesListPage /> },
      { path: '/inventory-moves', element: <MovementsListPage /> },
      { path: '/billing-home', element: <BillingSummaryPage /> },
      { path: '/billing', element: <BillingListPage /> },
      { path: '/finance', element: <FinanceListPage /> },
      { path: '/administration', element: <AdministrationSummaryPage /> },
      { path: '/users', element: <UsersListPage /> },
      { path: '/settings', element: <SettingsEditPage /> },
      { path: '/clients', element: <ClientsListPage /> },
      { path: '/clients/create', element: <ClientsCreatePage /> },
      { path: '/clients/:clientId/edit', element: <ClientsEditPage /> },
      { path: '/clients/:clientId/patients', element: <PatientsListPage /> },
      { path: '/clients/:clientId/patients/create', element: <PatientsCreatePage /> },
      { path: '/clients/:clientId/patients/:patientId/edit', element: <PatientsEditPage /> },
      { path: '/employees', element: <EmployeesListPage /> },
      { path: '/employees/create', element: <EmployeesCreatePage /> },
      { path: '/employees/:employeeId/edit', element: <EmployeesEditPage /> },
      { path: '/employees/:employeeId/permissions', element: <EmployeesPermissionsEditPage /> },
      { path: '/profile', element: <ProfileEditPage /> },
      { path: '/profile/password', element: <PasswordEditPage /> },
      { path: '/profile/sessions', element: <SessionsListPage /> },
      { path: '/disabled-account', element: <DisabledAccountPage /> },
      { path: '*', element: <NotFoundScreen /> },
    ],
  },
]

export default ownerRoutes
