import { lazy } from 'react'

export const DashboardPage = lazy(() => import('@/modules/superadmin/dashboard/page'))
export const DisabledAccountPage = lazy(() => import('@/modules/superadmin/disabled-account/page'))
export const PasswordEditPage = lazy(() => import('@/modules/superadmin/profile/password/password-edit/page'))
export const ProfileEditPage = lazy(() => import('@/modules/superadmin/profile/profile-edit/page'))
export const SessionsListPage = lazy(() => import('@/modules/superadmin/profile/sessions/sessions-list/page'))
export const OwnersCreatePage = lazy(() => import('@/modules/superadmin/owners/owners-create/page'))
export const OwnersEditPage = lazy(() => import('@/modules/superadmin/owners/owners-edit/page'))
export const OwnersListPage = lazy(() => import('@/modules/superadmin/owners/owners-list/page'))
export const OwnersPermissionsEditPage = lazy(() => import('@/modules/superadmin/owners/permissions/permissions-edit/page'))
export const SuperadminsCreatePage = lazy(() => import('@/modules/superadmin/superadmins/superadmins-create/page'))
export const SuperadminsEditPage = lazy(() => import('@/modules/superadmin/superadmins/superadmins-edit/page'))
export const SuperadminsListPage = lazy(() => import('@/modules/superadmin/superadmins/superadmins-list/page'))
export const SuperadminsPermissionsEditPage = lazy(() => import('@/modules/superadmin/superadmins/permissions/permissions-edit/page'))
