services:
  floci:
    image: floci/floci:latest
    user: root
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./floci-data:/app/data
    environment:
      FLOCI_STORAGE_MODE: hybrid
      FLOCI_SERVICES_LAMBDA_HOT_RELOAD_ENABLED: "true"
      FLOCI_SERVICES_LAMBDA_DEFAULT_TIMEOUT_SECONDS: "30"

